---
# docker-compose up -d
# docker-compose up --build
# docker-compose down
# docker-compose down -v

version: "3.8"

services:
 
  resumecreatoz:
    image:   resumecreatoz:local
    container_name:   resumecreatoz
    build:
      context: .
    ports:
      - 5000:8080

volumes:
  dbdata: